osx_image: xcode7
language: objective-c

before_install:
    - brew update
    - brew uninstall xctool && brew install xctool

script: xctool -project InputValidatorsExample/InputValidatorsExample.xcodeproj -scheme InputValidatorsExample -sdk iphonesimulator test
